Import all the required libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Load the data

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/ChaiCode Full Stack Data Science Cohort/Phase 2 - Machine Learning/LogisticRegression_Implementation_27July_11AM/diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

**EDA**

1.  How to tackle 0's in the above features like BP, Insulin, SkinThickness etc.
2.  Outliers -> Specially in insulin (right-skewed distribution)
3.  Feature Selection
4.  Data Standardization [StandardScaler, Min-Max Scaler]
5.  Data Imbalance


Data Split

In [ ]:
X = data.drop(columns='Outcome', axis = 1)
y = data['Outcome']

In [ ]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=44)

In [ ]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
407            0      101             62              0        0  21.9   
765            5      121             72             23      112  26.2   
558           11      103             68             40        0  46.2   
82             7       83             78             26       71  29.3   
165            6      104             74             18      156  29.9   
..           ...      ...            ...            ...      ...   ...   
96             2       92             62             28        0  31.6   
571            2      130             96              0        0  22.6   
173            1       79             60             42       48  43.5   
753            0      181             88             44      510  43.3   
419            3      129             64             29      115  26.4   

     DiabetesPedigreeFunction  Age  
407                     0.336   25  
765                     0.245   30  
558                     0.126   42  
82                      0.767   36  
165                     0.722   41  
..                        ...  ...  
96                      0.130   24  
571                     0.268   21  
173                     0.678   23  
753                     0.222   26  
419                     0.219   28  

[576 rows x 8 columns]

In [ ]:
y_train

407    0
765    0
558    0
82     0
165    1
      ..
96     0
571    0
173    0
753    1
419    1
Name: Outcome, Length: 576, dtype: int64

In [ ]:
# Data Imbalance
data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

1. Oversampling
2. Undersampling

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
from collections import Counter
Counter(y_train)

Counter({0: 385, 1: 191})

RandomOverSampler: Randomly duplicating samples from the minority class until both the classes have the same number of samples.

In [ ]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

model_over_sampling = RandomOverSampler(random_state=44)
X_train_over, y_train_over = model_over_sampling.fit_resample(X_train, y_train)

In [ ]:
Counter(y_train_over)

Counter({0: 385, 1: 385})

Advanced Over Sampling Techniques: SMOTE and ADASYN (Synthetic Data)

Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_over, y_train_over)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Model Prediction

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [ ]:
result_comparison = pd.DataFrame({'Actual Outcome': y_test, 'Predicted Outcome': y_pred})
result_comparison

Actual Outcome  Predicted Outcome
452               0                  0
370               1                  1
746               1                  1
122               0                  0
614               1                  1
..              ...                ...
458               1                  1
524               0                  0
43                1                  1
66                1                  0
76                0                  0

[192 rows x 2 columns]

In [ ]:
y_pred_prob = model.predict_proba(X_test)
y_pred_prob

array([[0.78242041, 0.21757959],
       [0.0187293 , 0.9812707 ],
       [0.32275249, 0.67724751],
       [0.72061127, 0.27938873],
       [0.19424639, 0.80575361],
       [0.37055578, 0.62944422],
       [0.46735027, 0.53264973],
       [0.87255415, 0.12744585],
       [0.79175859, 0.20824141],
       [0.61993447, 0.38006553],
       [0.54599588, 0.45400412],
       [0.44975883, 0.55024117],
       [0.83571464, 0.16428536],
       [0.83615915, 0.16384085],
       [0.8399807 , 0.1600193 ],
       [0.12382781, 0.87617219],
       [0.72121708, 0.27878292],
       [0.3965605 , 0.6034395 ],
       [0.89995592, 0.10004408],
       [0.36759492, 0.63240508],
       [0.62771246, 0.37228754],
       [0.19974254, 0.80025746],
       [0.73493314, 0.26506686],
       [0.52197349, 0.47802651],
       [0.95312775, 0.04687225],
       [0.76180201, 0.23819799],
       [0.49808958, 0.50191042],
       [0.43670203, 0.56329797],
       [0.85312044, 0.14687956],
       [0.16345053, 0.83654947],
       [0.

Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
confusion_matrix(y_test, y_pred)

array([[94, 21],
       [22, 55]])

In [ ]:
recall = recall_score(y_test, y_pred)
print(recall)

0.7142857142857143
